#! /bin/bash -e
set -o pipefail

show_help() {
cat << EOF
Usage: ${0##*/} [-hs] [-t INSTALL_DIR] ...
Install SimNIBS {{ version }} to the target directory

    -h               display this help and exit
    -t INSTALL_DIR   Installation directory. Default: ${HOME}/SimNIBS
    -s               Silent mode. Will not open the installation GUI
EOF
}

# Initialize our own variables:
INSTALL_DIR="$HOME/SimNIBS-{{ version }}"
INSTALL_LOG="$HOME/SimNIBS-{{ version }}/install.log"
silent=""

OPTIND=1
# Resetting OPTIND is necessary if getopts was used previously in the script.
# It is a good idea to make OPTIND local if you process options in a function.

while getopts hst: opt; do
    case $opt in
        h)
            show_help
            exit 0
            ;;
        s)  silent="--silent"
            ;;
        t)  INSTALL_DIR=$OPTARG
            ;;
        *)
            show_help >&2
            exit 1
            ;;
    esac
done
shift "$((OPTIND-1))"   # Discard the options and sentinel --
(
echo "Installing to ${INSTALL_DIR}"
CUR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd)"
mkdir -p "$INSTALL_DIR"
if [ -d "$INSTALL_DIR/simnibs_env" ]; then
    read -p "Found another SimNIBS installation in $INSTALL_DIR. Remove it? [y/N] :" REMOVE
fi
if [ $REMOVE == y || $REMOVE == Y ]; then
    rm -r "$INSTALL_DIR/simnibs_env"
fi
cp -R "$CUR_DIR/simnibs_env" "$INSTALL_DIR/simnibs_env"
source "$INSTALL_DIR/simnibs_env/bin/activate"
python "$CUR_DIR/postinstall_simnibs.py" -d "$INSTALL_DIR" --copy-matlab --setup-links --no-extra-coils $silent
find "$INSTALL_DIR/simnibs_env/bin/" -type f -exec grep -Iq . {} \; -exec sed -i 's+#!simnibs_env/bin/python+#!'"$INSTALL_DIR/simnibs_env/bin/python"'+' {} +
) 2>&1 | tee "$INSTALL_LOG"
