#!/bin/sh

set -e

########################################################
# This hook will switch between the internal and the   #
# release .gitignore files                             #
########################################################


repo_root=$(git rev-parse --show-toplevel)
current_branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$current_branch" = "release" ]; then
	cp "$repo_root/.gitignore.release" "$repo_root/.gitignore"
else
	cp "$repo_root/.gitignore.internal" "$repo_root/.gitignore"
fi
