#!/bin/sh

########################################################
# This hook will check if any folder called "internal/"#
# is being pushed to a remote release branch           #
########################################################


set -e

repo_root=$(git rev-parse --show-toplevel)
current_branch=$(git rev-parse --abbrev-ref HEAD)
# prevents the code from braking if no upstream is ter
if master_upstream=$(git rev-parse --abbrev-ref $current_branch@{u} 2>/dev/null); then
	master_has_upstream=true
else
	exit 0
fi
files_in_push=$(git diff --name-only "origin/$current_branch" 2>/dev/null);

if [ "$current_branch" = "release" ]; then
	has_internal=false
	for f in $files_in_push
	do
	    if [[ $f == *"internal/"* ]]; then
		    has_internal=true
		    echo "Found internal File: $f"
	    fi
	done
	if [ "$has_internal" = true ]; then
		echo "Cannot push to release branch: internal files found"
		echo "Please read the CONTRIBUTING.md file for instruction as to how to update the release branch"
		exit 2
	fi
fi
