# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple

__version__ = version = '3.2.4.dev988+geb8eaf45.d20230928'  # type: str
__version_tuple__ = version_tuple = (3, 2, 4, 'dev988', 'geb8eaf45.d20230928')  # type: Tuple[int | str, ...]
