# file generated by setuptools_scm
# don't change, don't track in version control
TYPE_CHECKING = False
if TYPE_CHECKING:
    from typing import Tuple

__version__ = version = '3.2.4.dev953+geb3ca739.d20230925'  # type: str
__version_tuple__ = version_tuple = (3, 2, 4, 'dev953', 'geb3ca739.d20230925')  # type: Tuple[int | str, ...]
