function [centers]=mesh_get_tetrahedron_centers(m)
  centers=(m.nodes(m.tetrahedra(:,1),:) + ...
    m.nodes(m.tetrahedra(:,2),:) + ...
  	m.nodes(m.tetrahedra(:,3),:) + ...
  	m.nodes(m.tetrahedra(:,4),:) ...
	)./4;
end
