from .g_function import g_function
from .ishigami import ishigami
from .lim_2002 import lim_2002
from .oakley_ohagan_2004 import oakley_ohagan_2004
from .peaks import peaks
from .sphere import *
from .sphere_fun import sphere_fun
from .sphere0_fun import sphere0_fun
from .welch_1992 import welch_1992
from .wing_weight import wing_weight
